### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by kingling** [gsetant/general-server-assistant#3]
试了一下，除了网络方面一言难尽以外，确实有效，是否考虑增加代理选项或者可以手动填写可用的jbus地址？
在网页上手动搜索有时能出结果。plex里自动一直没成功，是超时设置太短？手动匹配倒是找到了一两个。
也许是我网太差了，不fq情况下github都有问题，docker运行初始化时安装python的几个包都提示超时，不得不进docker的控制台手动指定pip源安装。

**Comment by chunsiyang** [comment]
此repository只解决gsetant相关问题，插件相关问题请勿在此提交。
此外使用gsetant需确保网络通畅
